# Redis Cluster Node 1 配置
port 7000
cluster-enabled yes
cluster-config-file nodes-7000.conf
cluster-node-timeout 5000
appendonly yes
appendfilename "appendonly-7000.aof"
requirepass __REDIS_PASSWORD__
masterauth __REDIS_PASSWORD__
# 集群通信端口
cluster-announce-ip 172.29.0.11
cluster-announce-port 7000
cluster-announce-bus-port 17000
