aof-load-truncated yes
port 7003
cluster-enabled yes
cluster-config-file nodes-7003.conf
cluster-node-timeout 5000
appendonly no
appendfilename "appendonly-7003.aof"
requirepass __REDIS_PASSWORD__
masterauth __REDIS_PASSWORD__
cluster-announce-ip 172.29.0.14
cluster-announce-port 7003
cluster-announce-bus-port 17003
