port 7004
cluster-enabled yes
cluster-config-file nodes-7004.conf
cluster-node-timeout 5000
appendonly yes
appendfilename "appendonly-7004.aof"
requirepass __REDIS_PASSWORD__
masterauth __REDIS_PASSWORD__
cluster-announce-ip 172.29.0.15
cluster-announce-port 7004
cluster-announce-bus-port 17004
