port 7005
cluster-enabled yes
cluster-config-file nodes-7005.conf
cluster-node-timeout 5000
appendonly yes
appendfilename "appendonly-7005.aof"
requirepass __REDIS_PASSWORD__
masterauth __REDIS_PASSWORD__
cluster-announce-ip 172.29.0.16
cluster-announce-port 7005
cluster-announce-bus-port 17005
